name: Update and Alert

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Build host info
      run: |
        uname -a
        cat /etc/os-release
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    -
      name: Build and Run
      env:
        GOOGLE_CHAT_TOKEN: ${{ secrets.GOOGLE_CHAT_TOKEN }}
        GOOGLE_CHAT_KEY: ${{ secrets.GOOGLE_CHAT_KEY }}
        GOOGLE_CHAT_SPACE: ${{ secrets.GOOGLE_CHAT_SPACE }}
      run: |
        make build && make run
    -
      name: Git Push if changes
      run: |
        git config --global user.email "2024.co2palm.letsgo@gmail.com" \
          && git config --global user.name "co2palm-yummy" \
          && git diff --exit-code || git commit -am "docs: update" \
          && git push origin gh-pages
